export const tableNames = {
	adminOperationLogs: "admin_operation_logs",
	adminPermissions: "admin_permissions",
	adminRolePermissions: "admin_role_permissions",
	adminRoles: "admin_roles",
	adminUserScopes: "admin_user_scopes",
	adminUserRoles: "admin_user_roles",
	adminUsers: "admin_users",
	afterSalesAttachments: "after_sales_attachments",
	afterSalesItems: "after_sales_items",
	afterSalesLogs: "after_sales_logs",
	afterSalesRequests: "after_sales_requests",
	analyticsEvents: "analytics_events",
	auditLogs: "audit_logs",
	brands: "brands",
	cartItems: "cart_items",
	carts: "carts",
	channelPerformanceStats: "channel_performance_stats",
	customerLtvStats: "customer_ltv_stats",
	dailySalesStats: "daily_sales_stats",
	domainEvents: "domain_events",
	eventProcessLogs: "event_process_logs",
	fulfillmentItems: "fulfillment_items",
	fulfillmentOrders: "fulfillment_orders",
	inventoryLocks: "inventory_locks",
	inventoryTransactions: "inventory_transactions",
	logisticsProviders: "logistics_providers",
	orders: "orders",
	orderEvents: "order_events",
	orderItems: "order_items",
	orderStatusLogs: "order_status_logs",
	paymentChannels: "payment_channels",
	paymentChargebacks: "payment_chargebacks",
	paymentOrders: "payment_orders",
	paymentRefunds: "payment_refunds",
	paymentTransactions: "payment_transactions",
	paymentWebhookEvents: "payment_webhook_events",
	productCategories: "product_categories",
	productAttributeValues: "product_attribute_values",
	productPerformanceStats: "product_performance_stats",
	productMedia: "product_media",
	productSkus: "product_skus",
	productTranslations: "product_translations",
	products: "products",
	shipmentTrackingEvents: "shipment_tracking_events",
	shipments: "shipments",
	siteCustomerAddresses: "site_customer_addresses",
	siteConfigs: "site_configs",
	siteCustomers: "site_customers",
	siteDomains: "site_domains",
	sites: "sites",
	skuInventory: "sku_inventory",
	skuPrices: "sku_prices",
	skuRegionRules: "sku_region_rules",
	users: "users",
	userAddresses: "user_addresses",
	userLoginLogs: "user_login_logs",
	verticalAttributeOptions: "vertical_attribute_options",
	verticalAttributes: "vertical_attributes",
	userProfiles: "user_profiles",
	verticals: "verticals",
	warehouses: "warehouses",
} as const;

export type TableName = (typeof tableNames)[keyof typeof tableNames];

export const highRiskTableNames = [
	tableNames.sites,
	tableNames.siteDomains,
	tableNames.siteConfigs,
	tableNames.orders,
	tableNames.orderItems,
	tableNames.orderStatusLogs,
	tableNames.paymentOrders,
	tableNames.paymentTransactions,
	tableNames.paymentWebhookEvents,
	tableNames.paymentRefunds,
	tableNames.paymentChargebacks,
	tableNames.skuInventory,
	tableNames.inventoryLocks,
	tableNames.inventoryTransactions,
	tableNames.fulfillmentOrders,
	tableNames.shipments,
	tableNames.shipmentTrackingEvents,
	tableNames.afterSalesRequests,
	tableNames.siteCustomers,
	tableNames.siteCustomerAddresses,
	tableNames.analyticsEvents,
	tableNames.dailySalesStats,
	tableNames.channelPerformanceStats,
	tableNames.productPerformanceStats,
	tableNames.customerLtvStats,
	tableNames.verticalAttributes,
	tableNames.productAttributeValues,
	tableNames.auditLogs,
	tableNames.adminOperationLogs,
	tableNames.adminUserScopes,
	tableNames.domainEvents,
] as const;

export type HighRiskTableName = (typeof highRiskTableNames)[number];
